language: ruby
rvm:
  - 4.0.3
python:
  - 2.7
before_install:
  - export LANG="en_US.UTF-8"
  - export LANGUAGE="en_US.UTF-8"
  - export LC_ALL="C.en_US.UTF-8"
install: 
  - gem install jekyll bundler ffi
  - bundle update
  - pip install --user -U pip
  - pip install --user awscli
script: 
  - bundle exec jekyll build
deploy:
  on:
    all_branches: true
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_DEFAULT_REGION
  bucket: "www.distributedgenomics.ca"
  skip_cleanup: true
  local_dir: _site
  acl: public_read

after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
