url: https://candig.github.io

# Site settings
title: CanDIG
email: Jonathan.Dursi@sickkids.ca
description: "CanDIG enables national-scale analysis of locally-controlled private genomic data"

collections:
  posts:
      output: true
      permalink: /posts/:title/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: github
    url: http://github.com/candig

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty

# Plugins
gems:
- jekyll-autoprefixer
- jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num"

include: [ "_pages", "_posts" ]
