url: https://www.distributedgenomics.ca

# Site settings
title: CanDIG
email: Jonathan.Dursi@sickkids.ca
description: "CanDIG enables national-scale analysis of locally-controlled private genomic data"

collections:
  posts:
      output: true
      permalink: /posts/:title/index.html
  releases:
      output: true
      permalink: /releases/:title/index.html

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/distribgenomics
  - title: github
    url: http://github.com/candig
  - title: envelope
    url: mailto:info@distributedgenomics.ca

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
plugins:
- jekyll-feed
- jekyll-autoprefixer

include: [ "_pages" ]
